[project]
name = "jp-en-translator-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "optimum[onnxruntime]",
    "transformers",
    "sentencepiece",
]

[project.scripts]
start = "uvicorn main:app --host 0.0.0.0 --port 8000"
